### ISSUE TITLE
URL in readme.md are not correct

### ISSUE THREAD

**Issue by lijc210** [gethue/compose#28]
curl -u hue:hue -X POST http://localhost:8005/editor/v1/query/sqlite --data 'statement=SELECT 100, 200'

Is that right?
curl -u hue:hue -X POST http://localhost:8005/api/editor/execute/sqlite --data 'statement=SELECT 100, 200'

**Comment by romainr** [comment]
Good catch, this was refactored recently and not update!

Would you be able to send a PR?

**Comment by lijc210** [comment]
I've sent PR
